added some update to playground
ahnafyy/mama-lang pull request #14
Opened 2024-01-26 15:22 UTC by nnlgsakib

Marge this PR. I will provide a complete overview of the playground after adding all the components .

2024-01-26 17:51 UTC, zhshakib commented on playground_v2/src/components/example.js
Nice work @nnlgsakib! Let's take it one step further, Just move the snippets to another file like `src/lib/snippets.js`, so that adding snippets becomes so easy for everyone.

2024-01-26 18:10 UTC, zhshakib requested changes
@nnlgsakib Have you tested your code? I was reviewing your code on my local machine and faced this issue, I don't know why is this happening! 

![image](https://github.com/ahnafyy/mama-lang/assets/46226834/fd2385d2-e687-423b-b75d-c9349bb615f0)

2024-01-26 19:59 UTC, ahnafyy commented
mama(s) will look at this and try to merge if things look good by sunday this week. If not change my name to Ahnaf OPRIO, mama. sorry for bottlenecking yall cause I LOVE LOVE all the contributions being made (better than I could have even done Id argue) just super busy :<

2024-01-26 21:23 UTC, ahnafyy commented
> @nnlgsakib Have you tested your code? I was reviewing your code on my local machine and faced this issue, I don't know why is this happening!
> 
> ![image](https://private-user-images.githubusercontent.com/46226834/300070581-fd2385d2-e687-423b-b75d-c9349bb615f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMDQ0MjAsIm5iZiI6MTcwNjMwNDEyMCwicGF0aCI6Ii80NjIyNjgzNC8zMDAwNzA1ODEtZmQyMzg1ZDItZTY4Ny00MjNiLWI3NWQtYzkzNDliYjYxNWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDIxMjIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NjA1YTE1Y2NiYzczMDVmNTczN2EzZTY0Nzg2ODAxY2E1MWQ3ZWJkNjMwNzJjZWNkYjY4NGY1OTY0YTA0MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2fVYJV9nECQdoshSolOUpX9eCn2edK-q2PDYMtxTVko)

Did you run an install inside the playground to make sure it has access to all the packages in node_modules it needs?
Give me a list of steps you did

2024-01-26 21:23 UTC, ahnafyy commented on playground_v2/src/components/example.js
This sounds like a good idea! 
@nnlgsakib if you got time wanna take a stab at it? if not I can try to as well.

2024-01-27 02:14 UTC, nnlgsakib commented
> @nnlgsakib Have you tested your code? I was reviewing your code on my local machine and faced this issue, I don't know why is this happening!
> 
> ![image](https://private-user-images.githubusercontent.com/46226834/300070581-fd2385d2-e687-423b-b75d-c9349bb615f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYzMjE1OTgsIm5iZiI6MTcwNjMyMTI5OCwicGF0aCI6Ii80NjIyNjgzNC8zMDAwNzA1ODEtZmQyMzg1ZDItZTY4Ny00MjNiLWI3NWQtYzkzNDliYjYxNWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI3VDAyMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4Y2MyYzM1YzdiNDU5NmI1YjcxMjkxNjVmNTViNjUwYWMxMzAxNmI2NmE2ZDEyNTI5OWJmY2I3ZjI2OTQ2MjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OpYYZHFL5JMbJCBeCaV1QSc0N_95toeuGD_pKqskDFs)

This is not a problem. It shows because I used custom syntax rules. You cut that error and everything will be fine. This does not cause any problems in production mode 

Example here: https://mama-lang-v2.vercel.app/

2024-01-29 17:04 UTC, ahnafyy approved these changes

2024-01-29 17:31 UTC, ahnafyy commented
@nnlgsakib mama arketa bar merge conflicts gula thik koro please and ill merge

2024-01-30 00:43 UTC, ahnafyy commented
goddamnit i cant git checkout your branch or else i was just gonna resolve the conflict on that one package-lock.json :"(

2024-01-30 03:57 UTC, ahnafyy commented
@nnlgsakib still showing
![Screenshot 2024-01-29 at 9 57 25 PM](https://github.com/ahnafyy/mama-lang/assets/52210609/851d03d3-e179-4ea7-9137-00daa8af81f0)

2024-01-30 04:39 UTC, closed without merging